#!/bin/bash

# Find files in the current directory and all subdirectories
# Filter by files ending in ~, .swp, or .swo
# Remove each file found
find . -type f \( -name "*~" -o -name "*.swp" -o -name "*.swo" \) -exec rm -f {} \;
echo "*~" >> .gitignore
echo "*.swp" >> .gitignore
echo "*.swo" >> .gitignore
