#!/usr/bin/env bash
#iterate from 1 to 100 printing fizzbuzz, fizz, buzz or number
i=1

until [ $i -gt 100 ]; do
    if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    else
        echo "$i"
    fi
    ((i++))
done
