#!/usr/bin/env bash
input_file="/etc/passwd"

# Set the Internal Field Separator (IFS) to colon (:)
IFS=":"

# Read each line of the /etc/passwd file
while read -r username password uid gid info homedir shell; do
    echo "The user $username is part of the group $gid gang, lives in $homedir, and rides $shell."
    echo "User $uid's place is protected by the passcode $password, more info about the user here: $info"
done < "$input_file"
