#!/usr/bin/env bash
# Loop while i is less than 10
counter=0

# Loop while counter is less than 10
while [ "$counter" -lt 10 ]; do
    echo "Best School"
    counter=$((counter + 1))  # Increment counter
done
