#!/usr/bin/env bash
#echo different messages according to the value of i
i=0

while [ $i -lt 8 ]
do
    echo "Best School"
    
    if [ $i -eq 2 ]; then
        echo "bad luck"
    fi
    
    if [ $i -eq 5 ]; then
        echo "good luck"
    fi
    
    i=$((i+1))
done
