#!/usr/bin/env bash
# Get the contents of the current directory and save them into an array to iterate
directory_contents=($(ls))

# Iterate through the array and print each item
for item in "${directory_contents[@]}"; do
    # Check if the item contains a "-" character
    if [[ $item == *-* ]]; then
        # Extract the substring after the first "-" character
        substring="${item#*-}"
        echo "$substring"
    fi
done
