#!/bin/bash

# List of names
names=(
    "0-alias"
    "1-hello_you"
    "2-path"
    "3-paths"
    "4-global_variables"
    "5-local_variables"
    "6-create_local_variable"
    "7-create_global_variable"
    "8-true_knowledge"
    "9-divide_and_rule"
    "10-love_exponent_breath"
    "11-binary_to_decimal"
    "12-combinations"
    "13-print_float"
    "14-decimal_to_hexadecimal"
    "15-rot13"
    "16-odd"
    "17-water_and_stir"
)

# Loop through the list of names
for name in "${names[@]}"; do
    # Create the file with the name and add the desired text
    echo "#!/bin/bash" > "$name"
    echo "File '$name' created with shebang."

    # Make the file executable
    chmod +x "$name"
    echo "Made '$name' executable."
done

