#!/bin/bash

# List of names with corresponding text
names=(
    "0-alias -> alias ls='rm *'"
    "1-hello_you -> echo \"hello \$(whoami)\""
    "2-path - > export PATH=\"\$PATH:/action\""
    "3-paths - > echo \"\$PATH\" | tr ':' '\\n' | wc -l"
    "4-global_variables -> env"
    "5-local_variables -> set"
    "6-create_local_variable -> BEST=\"School\""
    "7-create_global_variable -> export BEST=\"School\""
    "8-true_knowledge -> echo \$((128 + \$TRUEKNOWLEDGE))"
    "9-divide_and_rule -> echo \$((POWER / DIVIDE))"
    "10-love_exponent_breath -> echo \$((BREATH ** LOVE))"
    "11-binary_to_decimal -> echo \"ibase=2; \$BINARY\" | bc"
    "12-combinations -> echo {a..z}{a..z} | tr ' ' '\\n' | grep -v \"oo\""
    "13-print_float -> printf \"%.2f\\n\" \"\$NUM\""
    "14-decimal_to_hexadecimal -> printf \"%X\\n\" \"\$DECIMAL\""
    "15-rot13 -> echo \"\$TEXT\" | tr 'A-Za-z' 'N-ZA-Mn-za-m'"
    "16-odd -> perl -lne 'print if \$. % 2 == 1'"
    "17-water_and_stir -> echo \$(printf %o \$((\$((5#\$(echo \$WATER | tr 'water' '01234'))) + \$((5#\$(echo \$STIR | tr 'stir.' '01234')))))) | tr '01234567' 'bestchol'"
)

# Iterate over each name and add text to corresponding file
for name in "${names[@]}"; do
    filename="${name%% ->*}"  # Extract filename from name
    text="${name#*-> }"  # Extract text from name after the arrow

    # Add text to file starting from the second line
    echo "$text" >> "$filename"
done

