#!/usr/bin/env bash
#Management of processes
# Function to start manage_my_process
start_process() {
    if [ -f /var/run/my_process.pid ]; then
        echo "manage_my_process is already running."
    else
        # Start manage_my_process
        manage_my_process &
        PID=$!
        echo $PID > /var/run/my_process.pid
        echo "manage_my_process started"
    fi
}

# Function to stop manage_my_process
stop_process() {
    if [ -f /var/run/my_process.pid ]; then
        PID=$(cat /var/run/my_process.pid)
        kill "$PID"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

# Function to restart manage_my_process
restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

# Main script
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
