#!/usr/bin/env bash
#Management of processes
# Function to start manage_my_process
start_process() {
    if [ -f /var/run/my_process.pid ]; then
        echo "manage_my_process is already running"
    else
        # Start manage_my_process
        manage_my_process &
        PID=$!
        echo $PID > /var/run/my_process.pid
    fi
}

# Function to stop manage_my_process
stop_process() {
    if [ -f /var/run/my_process.pid ]; then
        PID=$(cat /var/run/my_process.pid)
        kill $PID
        rm /var/run/my_process.pid
    else
        echo "manage_my_process is not running."
    fi
}

# Function to restart manage_my_process
restart_process() {
    stop_process
    start_process
}

# Main script
if [ "$1" == "restart" ]; then
    restart_process
    echo "manage_my_process restarted"
elif [ "$1" == "start" ]; then
    start_process
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    stop_process
    echo "manage_my_process stopped"
else
    echo "Usage: $0 {start|stop|restart}"
fi
